-- Enable Row Level Security on every public table with no policies attached.
-- This app never queries Postgres through Supabase's auto-generated REST/GraphQL
-- API (no anon/authenticated client usage found in the codebase) - all reads and
-- writes go through Prisma using the table-owning role, which bypasses RLS
-- regardless of whether it is enabled. Enabling RLS here only closes the public
-- API exposure Supabase's security advisor flagged; it has zero effect on the app.
ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Appointment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BackupEmailSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Certificate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CertificateTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChatMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Circular" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Class" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClassFeeStructure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EventRegistration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExamSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExamSubject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExamTerm" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExamTermSection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExamType" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExamTypeSection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExtraFee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExtraFeeHeadTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeeDiscountApproval" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Homework" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HomeworkSubmission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LeaveRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Mark" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MarkComponent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NewsFeed" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NewsFeedLike" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ParentSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentFeeAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentWebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PettyCashExpense" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Refund" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "School" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SchoolSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Student" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentApplication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentFee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StudentLeaveRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyllabusTracking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyllabusUnit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SystemSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeacherAuditRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeacherDailyAttendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Timetable" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimetableEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TransferCertificate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_SchoolAdmin" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_SchoolTeacher" ENABLE ROW LEVEL SECURITY;
