import {
    LayoutDashboard,
    UserPlus,
    GraduationCap,
    Users,
    User,
    UserCheck,
    FileText,
    Award,
    AwardIcon,
    DollarSign,
    BookOpen,
    CalendarDays,
    Calendar,
    Briefcase,
    Newspaper,
    MessageSquare,
    Settings,
    LogOut,
} from "lucide-react";
import { SidebarItem } from "../../types/sidebar";
import { Permission } from "../../enums/permissions";

export const TEACHER_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/teacher?tab=dashboard",
        icon: LayoutDashboard,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Admission",
        tab: "admission",
        href: "/teacher?tab=admission",
        icon: UserPlus,
        permission: Permission.ADMISSION,
    },
    {
        label: "Classes",
        tab: "classes",
        href: "/teacher?tab=classes",
        icon: GraduationCap,
        permission: Permission.CLASSES,
    },
    {
        label: "Students",
        tab: "students",
        href: "/teacher?tab=students",
        icon: Users,
        permission: Permission.STUDENTS,
    },
    {
        label: "Student Details",
        tab: "student-details",
        href: "/teacher?tab=student-details",
        icon: User,
        permission: Permission.STUDENT_DETAILS,
    },
    {
        label: "Teachers",
        tab: "teachers",
        href: "/teacher?tab=teachers",
        icon: UserCheck,
        permission: Permission.TEACHERS,
    },
    {
        label: "Teacher Leaves",
        tab: "teacher-leaves",
        href: "/teacher?tab=teacher-leaves",
        icon: FileText,
        permission: Permission.TEACHER_LEAVES,
    },
    {
        label: "Teacher Audit",
        tab: "teacher-audit",
        href: "/teacher?tab=teacher-audit",
        icon: Award,
        permission: Permission.TEACHER_AUDIT,
    },
    {
        label: "Certificate Request",
        tab: "certificates",
        href: "/teacher?tab=certificates",
        icon: AwardIcon,
        permission: Permission.CERTIFICATES,
    },
    {
        label: "Fees & Payments",
        tab: "fees",
        href: "/teacher?tab=fees",
        icon: DollarSign,
        permission: Permission.FEES,
    },
    {
        label: "Homework",
        tab: "homework",
        href: "/teacher?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    },
    {
        label: "Timetable",
        tab: "timetable",
        href: "/teacher?tab=timetable",
        icon: CalendarDays,
        permission: Permission.TIMETABLE,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/teacher?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/teacher?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    },
    {
        label: "Exams & Syllabus",
        tab: "exams",
        href: "/teacher?tab=exams",
        icon: FileText,
        permission: Permission.EXAMS,
    },
    {
        label: "Worksops & Events",
        tab: "workshops",
        href: "/teacher?tab=workshops",
        icon: Briefcase,
        permission: Permission.WORKSHOPS,
    }, {
        label: "Newsfeed",
        tab: "newsfeed",
        href: "/teacher?tab=newsfeed",
        icon: Newspaper,
        permission: Permission.NEWSFEED,
    }, {
        label: "Parent Chat",
        tab: "chat",
        href: "/teacher?tab=chat",
        icon: MessageSquare,
        permission: Permission.CHAT,
    },
    {
        label: "Leave",
        tab: "leaves",
        href: "/teacher?tab=leaves",
        icon: FileText,
        permission: Permission.LEAVES,
    },
    {
        label: "Profile",
        tab: "profile",
        href: "/teacher?tab=profile",
        icon: User,
        permission: Permission.PROFILE,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/teacher?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Sign Out",
        action: "logout",
        icon: LogOut,
    },
];
