import {
    BookOpen,
    Calendar,
    ChartColumn,
    ClipboardList,
    MessageCircle,
    CreditCard,
    FileText,
    LogOut,
    User,
    Award,
    Briefcase,
    House,
    CalendarClock,
    CalendarDays,
    Settings,
} from "lucide-react";
import { SidebarItem } from "../../types/sidebar";
import { Permission } from "../../enums/permissions";

export const PARENT_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Analytics",
        description: "Performance Insights",
        tab: "analytics",
        href: "/frontend/pages/parent?tab=analytics",
        icon: ChartColumn,
        permission: Permission.ANALYTICS,
    requiresSubscription: true,
    },
    {
        label: "Home",
        tab: "dashboard",
        href: "/frontend/pages/parent?tab=dashboard",
        icon: House,
        permission: Permission.HOME,
    requiresSubscription: true,
    },
    {
        label: "Profile",
        tab: "profile",
        href: "/frontend/pages/parent?tab=profile",
        icon: User,
        permission: Permission.PROFILE,
        requiresSubscription: false,
    },
    {
        label: "Homework",
        tab: "homework",
        href: "/frontend/pages/parent?tab=homework",
        icon: BookOpen,
        permission: Permission.HOMEWORK,
    requiresSubscription: true,
    },
    {
        label: "Timetable",
        tab: "timetable",
        href: "/frontend/pages/parent?tab=timetable",
        icon: CalendarDays,
        permission: Permission.TIMETABLE,
    requiresSubscription: true,
    },
    {
        label: "Attendance",
        tab: "attendance",
        href: "/frontend/pages/parent?tab=attendance",
        icon: Calendar,
        permission: Permission.ATTENDANCE,
    requiresSubscription: true,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/frontend/pages/parent?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    requiresSubscription: true,
    },
    {
        label: "Exams & Syllabus",
        tab: "exams",
        href: "/frontend/pages/parent?tab=exams",
        icon: ClipboardList,
        permission: Permission.EXAMS,
    requiresSubscription: true,
    },
    {
        label: "Chat",
        tab: "chat",
        href: "/frontend/pages/parent?tab=chat",
        icon: MessageCircle,
        permission: Permission.CHAT,
    requiresSubscription: true,
    },
    {
        label: "Workshops",
        tab: "workshops",
        href: "/frontend/pages/parent?tab=workshops",
        icon: Briefcase,
        permission: Permission.WORKSHOPS,
    requiresSubscription: true,
    },
    {
        label: "Certificates",
        tab: "certificates",
        href: "/frontend/pages/parent?tab=certificates",
        icon: FileText,
        permission: Permission.CERTIFICATES,
    requiresSubscription: true,
    },
    {
        label: "Fees",
        tab: "fees",
        href: "/frontend/pages/parent?tab=fees",
        icon: CreditCard,
        permission: Permission.FEES,
        requiresSubscription: false,
    },
    {
        label: "Leave Application",
        tab: "leave",
        href: "/frontend/pages/parent?tab=leave",
        icon: CalendarClock,
        permission: Permission.STUDENT_LEAVE,
    requiresSubscription: true,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/frontend/pages/parent?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
        requiresSubscription: false,
    },
    {
        label: "Subscription",
        tab: "subscription",
        href: "/frontend/pages/parent?tab=subscription",
        icon: CreditCard,
        permission: Permission.FEES,
        requiresSubscription: false,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];
