import {
    Layout,
    GraduationCap,
    Users,
    UserPlus,
    User,
    UserCheck,
    CalendarDays,
    FileText,
    Award,
    Calendar,
    Newspaper,
    Scroll,
    AwardIcon,
    DollarSign,
    ClipboardList,
    ChartColumn,
    Settings,
    LogOut,
} from "lucide-react";
import { SidebarItem } from "../../types/sidebar";
import { Permission } from "../../enums/permissions";

export const SCHOOLADMIN_MENU_ITEMS: SidebarItem[] = [
    {
        label: "Dashboard",
        tab: "dashboard",
        href: "/schooladmin?tab=dashboard",
        icon: Layout,
        permission: Permission.DASHBOARD,
    },
    {
        label: "Classes",
        tab: "classes",
        href: "/schooladmin?tab=classes",
        icon: GraduationCap,
        permission: Permission.CLASSES,
    },
    {
        label: "Students",
        tab: "students",
        href: "/schooladmin?tab=students",
        icon: Users,
        permission: Permission.STUDENTS,
    },
    {
        label: "Admission",
        tab: "admission",
        href: "/schooladmin?tab=admission",
        icon: UserPlus,
        permission: Permission.ADMISSION,
    },
    {
        label: "Add User",
        tab: "add-user",
        href: "/schooladmin?tab=add-user",
        icon: UserPlus,
        permission: Permission.NEW_USER,
    }, {
        label: "Student Details",
        tab: "student-details",
        href: "/schooladmin?tab=student-details",
        icon: User,
        permission: Permission.STUDENT_DETAILS,
    },
    {
        label: "Teachers",
        tab: "teachers",
        href: "/schooladmin?tab=teachers",
        icon: UserCheck,
        permission: Permission.TEACHERS,
    },
    {
        label: "Timetable",
        tab: "timetable",
        href: "/schooladmin?tab=timetable",
        icon: CalendarDays,
        permission: Permission.TIMETABLE,
    },
    {
        label: "Teacher Leaves",
        tab: "teacher-leaves",
        href: "/schooladmin?tab=teacher-leaves",
        icon: FileText,
        permission: Permission.TEACHER_LEAVES,
    },
    {
        label: "Teacher Audit",
        tab: "teacher-audit",
        href: "/schooladmin?tab=teacher-audit",
        icon: Award,
        permission: Permission.TEACHER_AUDIT,
    },
    {
        label: "Workshops & Events",
        tab: "workshops",
        href: "/schooladmin?tab=workshops",
        icon: Calendar,
        permission: Permission.WORKSHOPS,
    },
    {
        label: "Newsfeed",
        tab: "newsfeed",
        href: "/schooladmin?tab=newsfeed",
        icon: Newspaper,
        permission: Permission.NEWSFEED,
    }, {
        label: "Circulars",
        tab: "circulars",
        href: "/schooladmin?tab=circulars",
        icon: Scroll,
        permission: Permission.CIRCULARS,
    },
    {
        label: "Certificate Request",
        tab: "certificates",
        href: "/schooladmin?tab=certificates",
        icon: AwardIcon,
        permission: Permission.CERTIFICATES,
    },
    {
        label: "Fees",
        tab: "fees",
        href: "/schooladmin/fees",
        icon: DollarSign,
        permission: Permission.FEES,
    },
    {
        label: "Exams",
        tab: "exams",
        href: "/schooladmin?tab=exams",
        icon: ClipboardList,
        permission: Permission.EXAMS,
    },
    {
        label: "Marks",
        tab: "marks",
        href: "/schooladmin?tab=marks",
        icon: Award,
        permission: Permission.MARKS,
    },
    {
        label: "Analysis",
        tab: "analysis",
        href: "/schooladmin/analysis",
        icon: ChartColumn,
        permission: Permission.ANALYSIS,
    },
    {
        label: "Settings",
        tab: "settings",
        href: "/schooladmin?tab=settings",
        icon: Settings,
        permission: Permission.SETTINGS,
    },
    {
        label: "Logout",
        icon: LogOut,
        action: "logout",
    },
];

export const SCHOOLADMIN_TAB_TITLES: Record<string, string> = {
    dashboard: "Dashboard",
    students: "Students",
    admission: "Admission",
    teachers: "Teachers",
    classes: "Classes",
    "teacher-leaves": "Teacher Leaves",
    "tc-approvals": "TC Approvals",
    payments: "Payments",
    workshops: "Workshops & Events",
    newsfeed: "Newsfeed",
    exams: "Exams",
    marks: "Marks",
    analysis: "Analysis",
    "student-details": "Student Details",
    "add-user": "Add User",
    "teacher-audit": "Teacher Audit",
    timetable: "Timetable",
    circulars: "Circulars",
    certificates: "Certificate Requests",
    fees: "Fees",
    settings: "Settings",
};
