import { ClassItem, StudentFormState } from "../types";

export const DEFAULT_FORM: StudentFormState = {
  name: "",
  rollNo: "",
  penNumber: "",
  apaarId: "",
  gender: "",
  residencyType: "Day Scholar",
  dob: "",
  classId: "",
  section: "",
  status: "Active",
  fatherName: "",
  motherName: "",
  occupation: "",
  officeAddress: "",
  phoneNo: "",
  email: "",
  address: "",
  aadhaarNo: "",
  parentAadharNo: "",
  parentWhatsapp: "",
  bankAccountNo: "",
  totalFee: "",
  discountPercent: "",
  applicationFee: "",
  admissionFee: "",
  previousSchool: "",
  houseNo: "",
  street: "",
  city: "",
  town: "",
  state: "",
  pinCode: "",
  nationality: "Indian",
  languagesAtHome: "",
  caste: "",
  religion: "",
  emergencyFatherNo: "",
  emergencyMotherNo: "",
  emergencyGuardianNo: "",
  subjects: [],
};

export const EMPTY_CLASSES: ClassItem[] = [];
