/**
 * Explicit Prisma selects that omit `workflowStatus` so queries work before the
 * `workflowStatus` / `AdmissionWorkflowStatus` migration is applied on PostgreSQL.
 */

export const studentApplicationDetailSelect = {
  id: true,
  schoolId: true,
  classId: true,
  className: true,
  section: true,
  studentId: true,
  applicationNo: true,
  fedenaNo: true,
  admissionNo: true,
  gradeSought: true,
  boardingType: true,
  residencyType: true,
  totalFee: true,
  discountPercent: true,
  applicationFee: true,
  admissionFee: true,
  applicationFeePaid: true,
  applicationFeePaidAt: true,
  applicationFeePaymentMode: true,
  applicationFeePaymentMethod: true,
  admissionFeePaid: true,
  admissionFeePaidAt: true,
  admissionFeePaymentMode: true,
  admissionFeePaymentMethod: true,
  rollNo: true,
  penNumber: true,
  apaarId: true,
  firstName: true,
  middleName: true,
  lastName: true,
  gender: true,
  dateOfBirth: true,
  aadharNo: true,
  firstLanguage: true,
  nationality: true,
  languagesAtHome: true,
  caste: true,
  religion: true,
  houseNo: true,
  street: true,
  city: true,
  town: true,
  state: true,
  pinCode: true,
  parentName: true,
  motherName: true,
  motherAadharNo: true,
  motherEmail: true,
  parentOccupation: true,
  officeAddress: true,
  parentPhone: true,
  parentEmail: true,
  parentAadharNo: true,
  parentWhatsapp: true,
  bankAccountNo: true,
  previousSchoolName: true,
  previousSchoolAddress: true,
  emergencyFatherNo: true,
  emergencyMotherNo: true,
  emergencyGuardianNo: true,
  createdAt: true,
  updatedAt: true,
} as const;

/** Fields needed when linking an admission to a new student (student create API). */
export const studentApplicationForStudentCreateSelect = {
  id: true,
  studentId: true,
  firstName: true,
  middleName: true,
  lastName: true,
  parentName: true,
  aadharNo: true,
  parentPhone: true,
  parentEmail: true,
  dateOfBirth: true,
  classId: true,
  applicationFee: true,
  admissionFee: true,
  gender: true,
  residencyType: true,
  previousSchoolName: true,
  penNumber: true,
  apaarId: true,
  houseNo: true,
  street: true,
  town: true,
  city: true,
  state: true,
  pinCode: true,
  class: { select: { id: true } },
} as const;
